### ISSUE TITLE
prod and qa bug with fasta / protein sequence  option

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/service-sequence-retrieval#23]
(same error in prod and qa but since in qa dan improved the message to the user, we can see the sequence  we return to the user , copied below)

https://qa.fungidb.org/fungidb/app/record/gene/download/C1_00010W_B

the returned sequence is correct but we say there is an error
>C1_00010W_B-T | error_code=TRUNCATED_END_OF_SEQUENCE
MTSFNEFFSADFFVNSDQKNTHLTAYTTQTYSKQAVVPPFRLSLCLEPISVSLSPDLHCP
FLSKTRLKYYFNTAHYYQDLHCSSMFRCPTAVLDSGLSLKITRDTAKIGVPL

in gene page check the protein sequence is the same
 https://qa.fungidb.org/fungidb/app/record/gene/C1_00010W_B#Sequences

Predicted Protein Sequence
113 aa
Copy to clipboard
MTSFNEFFSADFFVNSDQKNTHLTAYTTQTYSKQAVVPPFRLSLCLEPISVSLSPDLHCPFLSKTRLKYYFNTAHYYQDLHCSSMFRCPTAVLDSGLSLKITRDTAKIGVPL

<img width="1128" alt="Screenshot 2024-03-18 at 5 07 10 PM" src="https://github.com/VEuPathDB/service-sequence-retrieval/assets/16354313/85f966a7-18ba-4e7e-a106-60413a714b48">

**Comment by bgajria** [comment]
This is fixed on Live and QA Fungi sites.
https://redmine.apidb.org/issues/53932
